kind: pipeline
type: docker
name: nuxt-pipeline


steps:
  - name: install
    image: node:22-alpine
    commands:
      - npm install
    when:
      event:
        - push
        - pull_request

  - name: build
    image: node:22-alpine
    commands:
      - npm run build
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/projects/ryusu.id
        - git pull
        - sudo docker build -t ryusu777/ryusu.id:latest .
        - sudo docker push ryusu777/ryusu.id:latest
        - kubectl rollout restart deployment web -n ryusu-id
    depends_on:
      - build
    when:
      branch:
        - master
      event:
        - push

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
