kind: pipeline
type: docker
name: nuxt-pipeline

steps:
  - name: install
    image: node:22-alpine
    commands:
      - npm install
    when:
      event:
        - push
        - pull_request

  - name: build
    image: node:22-alpine
    commands:
      - npm run build
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      environment:
        SSH_KEY:
          from_secret: git_ssh_key
      port: 22
      script:
        - cd ~/docker-composes/landing-page/ryusu.id
        - mkdir -p ~/.ssh
        - echo "$SSH_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - touch ~/.ssh/known_hosts
        - ssh-keyscan -H github.com > ~/.ssh/known_hosts
        - git pull
        - sudo docker-compose down
        - sudo docker-compose up --build -d
    depends_on:
      - build
    when:
      branch:
        - master
      event:
        - push

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
