kind: pipeline
type: kubernetes
name: nuxt-pipeline

steps:
  - name: install
    image: node:22-alpine
    commands:
      - npm install
    when:
      event:
        - push
        - pull_request

  - name: build
    image: node:22-alpine
    commands:
      - npm run build
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request
        - custom

  - name: deploy
    image: bitnami/kubectl:latest
    commands:
      - kubectl rollout restart deployment web -n ryusu-id
    depends_on:
      - build
    volumes:
      - name: kubeconfig
        path: /.kube/config
    when:
      branch:
        - master
      event:
        - push
        - custom

volumes:
  - name: kubeconfig
    path: 
      from_secret: kubeconfig_path

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - custom
