kind: pipeline
type: kubernetes
name: nuxt-pipeline

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ryusu777/ryusu.id
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - master
      event:
        - push

  - name: deploy
    image: bitnami/kubectl:latest
    commands:
      - kubectl rollout restart deployment web -n ryusu-id
    depends_on:
      - build-and-push
    when:
      branch:
        - master
      event:
        - push

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - custom
