kind: pipeline
type: docker
name: nuxt-pipeline

steps:
  - name: install
    image: node:22-alpine
    commands:
      - npm install
    when:
      event:
        - push
        - pull_request

  - name: lint
    image: node:22-alpine
    commands:
      - npm run lint
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request

  - name: build
    image: node:22-alpine
    commands:
      - npm run build
    depends_on:
      - lint
    when:
      event:
        - push
        - pull_request

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/docker-composes/landing-page/ryusu.id
        - git pull
        - sudo docker-compose down
        - sudo docker-compose up --build -d
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
